import type { Metadata } from "next";
import { ArrowUpRight } from "lucide-react";
import { PageHero } from "../site-chrome";
import { sitePath } from "../site-paths";

export const metadata: Metadata = { title: "News | Judith Njoku-Vowels, PhD" };

type NewsItem = { date: string; category: string; title: string; text: string; href?: string };

const journey: NewsItem[] = [
  { date: "June 17, 2026", category: "Virtual presentation", title: "PANDA presented virtually at i3CE 2026", text: "I presented PANDA, our lightweight digital twin framework for smart parking management, during the virtual program of the ASCE International Conference on Computing in Civil Engineering. The conference was held June 14 to 17 at Songdo Convensia in Songdo, Incheon, South Korea.", href: "https://www.i3ce2026.com/about/03.html" },
  { date: "June 3 to 7, 2026", category: "Conference", title: "OmniRestore presented at the IEEE/CVF CVPR Workshops in Denver", text: "An exciting milestone for our Secure Sensing and Learning Research Lab team. I presented OmniRestore, our parameter-efficient framework for universal adverse-weather image restoration, at the Colorado Convention Center in Denver, Colorado.", href: "https://openaccess.thecvf.com/content/CVPR2026W/NTIRE/papers/Njoku_OmniRestore_A_Parameter-Efficient_Framework_for_Universal_Adverse-Weather_Image_Restoration_CVPRW_2026_paper.pdf" },
  { date: "April 2026", category: "Acceptance", title: "OmniRestore accepted at CVPR Workshops", text: "Congratulations to our full research team on this milestone for efficient restoration across rain, snow, haze, and other adverse conditions.", href: "https://judith989.github.io/CVPRW2026_OmniRestore/" },
  { date: "March 2026", category: "Acceptance", title: "PANDA accepted at i3CE 2026", text: "Congratulations to our coauthor team on the acceptance of PANDA, a lightweight digital twin framework for smart parking management.", href: "https://scholar.google.com/scholar?q=%22PANDA%3A+A+Lightweight+Digital+Twin+Framework+for+Smart+Parking+Management%22" },
  { date: "August 29, 2025", category: "Appointment", title: "Joined the University of Wyoming and the Secure Sensing and Learning Research Lab", text: "I began my postdoctoral chapter in Laramie, Wyoming, joining the University of Wyoming and the Secure Sensing and Learning Research Lab. This transition expanded my research into robust computer vision, smart infrastructure, and AI-enabled systems for rural and autonomous environments.", href: "/about" },
  { date: "August 22, 2025", category: "Education", title: "PhD degree conferred", text: "I received my PhD in IT Convergence Engineering from Kumoh National Institute of Technology in South Korea. BatteryMetrix brought together the central themes of my doctoral work: predictive battery intelligence, explainable AI, secure lifecycle records, and immersive digital twins.", href: "/gallery" },
  { date: "July 8 to 11, 2025", category: "Conference", title: "ICUFN 2025 at Iscte in Lisbon, Portugal", text: "At ICUFN 2025, the 16th International Conference on Ubiquitous and Future Networks, I shared research spanning BridgeSync for secure bridge monitoring, interactive battery digital twins, and emerging communication systems. The conference was held at Iscte, University Institute of Lisbon in Portugal.", href: "/gallery" },
  { date: "June 15 to 20, 2025", category: "Conference", title: "IEEE IAS Annual Meeting 2025 in Taipei City, Taiwan", text: "Congratulations to our coauthor team on presenting explainable and model-agnostic energy-consumption prediction research at the IEEE Industry Applications Society Annual Meeting in Taipei City, Taiwan.", href: "https://doi.org/10.1109/IAS62731.2025.11061571" },
  { date: "April 23 to 25, 2025", category: "Conference presentation", title: "PureTwin presented at JCCI 2025 in Sokcho, South Korea", text: "At JCCI 2025, the 35th Joint Conference on Telecommunications and Information, I presented PureTwin, an interactive non-fungible digital twin framework for battery management systems. The conference was held at Sokcho Sonocalm Delpino Resort in South Korea.", href: "/gallery" },
  { date: "February 2025", category: "Conference", title: "ICAIIC 2025 in Fukuoka, Japan", text: "I presented our trustworthy battery-management research at the International Conference on Artificial Intelligence in Information and Communication. The paper combined digital twins, explainable AI, and blockchain to make battery predictions more interpretable and accountable.", href: "https://doi.org/10.1109/ICAIIC64266.2025.10920782" },
  { date: "November 2024", category: "Conference", title: "KICS Fall Conference 2024 in South Korea", text: "I shared emerging digital-twin and intelligent-systems research with the Korean communications community, receiving technical feedback that helped connect the system architecture to practical deployment questions.", href: "/gallery" },
  { date: "October 2024", category: "Conference", title: "ICTC 2024 on Jeju Island, South Korea", text: "Our team presented two papers at the International Conference on Information and Communication Technology Convergence: EL-Alert for explainable military surveillance and a review of intrusion detection in MQTT-enabled IoT networks.", href: "https://doi.org/10.1109/ICTC62082.2024.10826893" },
  { date: "August 7 to 9, 2024", category: "Conference", title: "TwinMil presented at ICMIC 2024 in Kuala Lumpur", text: "I presented TwinMil, our semantic-segmentation digital twin framework for military surveillance, at the 3rd International Conference on Mobile, Military and Maritime IT Convergence at the Concorde Hotel in Kuala Lumpur, Malaysia.", href: "https://public.thinkonweb.com/sites/icmic2024" },
  { date: "2024", category: "Education", title: "Defended the BatteryMetrix PhD thesis", text: "I successfully defended BatteryMetrix: A User-Centric Digital Twin Framework for Predictive, Explainable, and Secure Battery Management Systems at Kumoh National Institute of Technology.", href: "/research/batterymetrix" },
  { date: "2024", category: "Appointment", title: "Joined Michigan State University as a Visiting Research Scholar", text: "At Michigan State University in East Lansing, Michigan, I extended my systems research into agricultural AI, multimodal learning for livestock and soil analysis, greenhouse sensing, and smart systems for specialty-crop production.", href: "/about" },
  { date: "April 24 to 26, 2024", category: "Conference presentation", title: "Explainable battery digital twins presented at JCCI 2024 in Busan", text: "At JCCI 2024, the 34th Joint Conference on Telecommunications and Information, I presented SHAP-based Explainable Model-in-the-Loop for Digital Twins in Battery Management Systems. The conference was held at Busan Paradise Hotel in Busan, South Korea.", href: "/gallery" },
  { date: "November 2023", category: "Conference presentation", title: "Maritime speaker identification presented at ICMIC 2023", text: "At the 2nd International Conference on Maritime IT Convergence at Shilla Stay on Jeju Island, South Korea, I presented Multi-Feature Concatenation for Speech Dependent Automatic Speaker Identification in Maritime Autonomous Vehicles with Cosmas Ifeanyi Nwakanma, Jae-Min Lee, and Dong-Seong Kim.", href: "https://www.researchgate.net/publication/373755841_Multi-Feature_Concatenation_for_Speech_Dependent_Automatic_Speaker_Identification_in_Maritime_Autonomous_Vehicles" },
  { date: "October 2023", category: "Conference presentation", title: "MetaHate presented at ICTC 2023", text: "At the 14th International Conference on Information and Communication Technology Convergence on Jeju Island, South Korea, I presented MetaHate: Text-based Hate Speech Detection for Metaverse Applications Using Deep Learning with Anthony Uchenna Eneh, Cosmas Ifeanyi Nwakanma, Jae-Min Lee, and Dong-Seong Kim.", href: "https://ieeexplore.ieee.org/document/10392437" },
  { date: "July 4 to 7, 2023", category: "Conference presentation", title: "A transportation metaverse demonstrated at ICUFN 2023 in Paris", text: "At ECE, Ecole d'Ingenieurs in Paris, France, I presented Building a Metaverse for Transportation Systems: A Brief Review and Demonstration with Cosmas Ifeanyi Nwakanma and Dong-Seong Kim. The paper examined parking detection, parking assistance, lane detection, and emerging metaverse applications for transportation.", href: "https://doi.org/10.1109/ICUFN57995.2023.10199405" },
  { date: "2023", category: "Conference presentation", title: "Battery digital twin and metaverse presented at KICS Summer 2023", text: "At the KICS Summer Conference at Ramada Plaza on Jeju Island, South Korea, I presented Metaverse and Digital Twin for BMS using MATLAB and Unreal Engine with Ebuka Chinaechetam Nkoro, Robin Matthew Medina, Paul Michael Custodio, Cosmas Ifeanyi Nwakanma, Jae-Min Lee, and Dong-Seong Kim.", href: "https://www.researchgate.net/publication/371911768_Metaverse_and_Digital_Twin_for_BMS_using_MATLAB_and_Unreal_Engine" },
  { date: "April 26 to 28, 2023", category: "Conference presentation", title: "Battery model selection presented at JCCI 2023", text: "At the 33rd Joint Conference on Communication and Information at Hidden Bay Hotel in Yeosu, South Korea, I presented Model Comparison and Selection for Battery Digital Twin Development using PyBaMM with Cosmas Ifeanyi Nwakanma, Jae-Min Lee, and Dong-Seong Kim.", href: "https://www.researchgate.net/publication/370636700_Model_Comparison_and_Selection_for_Battery_Digital_Twin_Development_using_PyBaMM" },
  { date: "2022", category: "Conference presentation", title: "Lithium-ion battery digital twin analysis presented at KICS Fall 2022", text: "At Lahan Select Hotel in Gyeongju, South Korea, I presented Analysis of Deep Neural Networks-Based Digital Twin for Lithium-ion Batteries with Robin Matthew Medina, Ebuka Chinaechetam Nkoro, Cosmas Ifeanyi Nwakanma, Jae-Min Lee, and Dong-Seong Kim. This work became an important foundation for BatteryMetrix.", href: "https://www.researchgate.net/publication/365878142_Analysis_of_Deep_Neural_Networks-Based_Digital_Twin_for_Lithium-ion_Batteries" },
  { date: "October 2022", category: "Conference presentation", title: "SmartParking object detection presented at ICTC 2022", text: "At the 13th International Conference on Information and Communication Technology Convergence at Ramada Plaza on Jeju Island, South Korea, our team presented State-of-the-Art Object Detectors for Vehicle, Pedestrian, and Traffic Sign Detection for Smart Parking Systems.", href: "https://doi.org/10.1109/ICTC55196.2022.9952856" },
  { date: "October 19 to 21, 2022", category: "Conference presentation", title: "5G and the metaverse presented at APCC 2022", text: "At the 27th Asia-Pacific Conference on Communications at Ramada Plaza on Jeju Island, South Korea, I presented The Role of 5G Wireless Communication System in the Metaverse with Robin Matthew Medina, Cosmas Ifeanyi Nwakanma, and Dong-Seong Kim.", href: "https://scholar.google.com/scholar?q=%22The+Role+of+5G+Wireless+Communication+System+in+the+Metaverse%22" },
  { date: "2022", category: "Conference presentation", title: "Keyword spotting for autonomous vehicles presented at KICS Summer 2022", text: "At the KICS Summer Conference at the Grand Hyatt on Jeju Island, South Korea, I presented Evaluation of Spectrograms for Keyword Spotting in Control of Autonomous Vehicles for the Metaverse with Cosmas Ifeanyi Nwakanma and Dong-Seong Kim.", href: "https://www.researchgate.net/publication/361558505_Evaluation_of_Spectrograms_for_Keyword_Spotting_in_Control_of_Autonomous_Vehicles_for_The_Metaverse" },
  { date: "February 9 to 11, 2022", category: "Conference presentation", title: "Real-time scene recognition presented at KICS Winter 2022", text: "At Alpensia Resort in Pyeongchang, Gangwon Province, South Korea, I presented Real-time Deep Learning-based Scene Recognition Model for Metaverse Applications with Gabriel Amaizu, Jae-Min Lee, and Dong-Seong Kim.", href: "https://www.researchgate.net/publication/358947984_Real-time_Deep_Learning-based_Scene_Recognition_Model_For_Metaverse_Applications" },
  { date: "2022", category: "Research transition", title: "Joined the Networked Systems Laboratory for my PhD", text: "At Kumoh National Institute of Technology in Gumi, South Korea, I moved from wireless communication research into digital twins, explainable AI, cybersecurity, and battery-management systems. This was the beginning of the BatteryMetrix research program.", href: "/about" },
  { date: "August 20, 2021", category: "Education", title: "MSc degree conferred", text: "I received my MSc in Electronics Engineering from Kumoh National Institute of Technology in Gumi, South Korea, after developing deep-learning methods for wireless communication systems.", href: "/gallery" },
  { date: "February 3 to 5, 2021", category: "Virtual presentation", title: "Two spectrum-allocation papers presented virtually at KICS Winter 2021", text: "During the KICS Winter Conference hosted at YongPyong Resort in Pyeongchang, Gangwon Province, South Korea, I presented Optimizing Spectrum Sharing in UAV-to-UAV Cellular Communications and Predicting Target Data Rates for Dynamic Spectrum Allocation Using Gaussian Process Regression virtually with my Future Communications Systems Lab collaborators.", href: "https://www.researchgate.net/publication/358916150_Optimizing_Spectrum_Sharing_in_UAV-to-UAV_Cellular_Communications" },
  { date: "2020", category: "Conference presentation", title: "Radar waveform recognition presented at KICS Summer Conference", text: "In Pyeongchang, South Korea, I presented Automatic Radar Waveform Recognition using the Wigner-Ville Distribution and AlexNet-SVM with Manuel Eugenio Morocho-Cayamcela and Wansu Lim. The work combined time-frequency representations with deep feature extraction and support vector classification.", href: "https://www.researchgate.net/publication/343712491_Automatic_Radar_Waveform_Recognition_using_the_Wigner-Ville_distribution_and_AlexNet-SVM" },
  { date: "February 2020", category: "Conference", title: "ICAIIC 2020", text: "My first international conference chapter explored how autoencoders could reshape learning-enabled wireless communication systems.", href: "https://scholar.google.com/scholar?q=%22Learning+to+Communicate+with+Autoencoders%22+Njoku" },
  { date: "2019", category: "Research transition", title: "Joined the Future Communications Systems Laboratory", text: "After moving to Gumi, South Korea, for my MSc in Electronics Engineering, I joined the Future Communications Systems Laboratory at Kumoh National Institute of Technology. There I began working on modulation recognition, channel autoencoders, and deep learning for wireless communication.", href: "/about" },
  { date: "2019", category: "Conference presentation", title: "Blockchain and spectrum management presented at KICS", text: "I presented Hunger Marketing and Blockchain Technology: Applications in Wireless Spectrum Management with Manuel Eugenio Morocho-Cayamcela and Wansu Lim. This early work explored how demand-shaping strategies and distributed ledgers could support wireless spectrum management.", href: "https://scholar.google.com/scholar?q=%22Hunger+marketing+and+Blockchain+Technology%22" },
  { date: "2014", category: "Education", title: "BEng degree conferred", text: "I earned my Bachelor of Engineering in Petroleum Engineering from the Federal University of Technology, Owerri, Nigeria. That foundation taught me to approach engineering problems as interconnected physical systems.", href: "/gallery" },
];

function NewsCard({ item }: { item: NewsItem }) {
  const external = item.href?.startsWith("http");
  return (
    <article>
      <div className="news-year">{item.date}</div>
      <div className="news-dot" />
      <div className="news-card">
        <span>{item.category}</span>
        <h2>{item.title}</h2>
        <p>{item.text}</p>
        {item.href && <a href={external ? item.href : sitePath(item.href)} target={external ? "_blank" : undefined} rel={external ? "noreferrer" : undefined}>Read more <ArrowUpRight size={14} /></a>}
      </div>
    </article>
  );
}

export default function NewsPage() {
  return (
    <main>
      <PageHero label="News and milestones" title="What I am presenting, building, and celebrating." text="Follow the conference journeys, academic milestones, collaborations, and shared wins that continue to shape my work." />
      <section className="page-section news-timeline">
        {journey.map((item) => <NewsCard item={item} key={`${item.date}-${item.title}`} />)}
      </section>
    </main>
  );
}
